trigger:
- master

jobs:
- job: Build
  displayName: 'Versioning, Docker'
  timeoutInMinutes: 15
  pool:
    vmImage: 'Ubuntu-18.04'
  variables:
  - group: uru
  - name: image_name
    value: uru

  steps:
  # 1. Install .NET SDK 3.1
  - task: UseDotNet@2
    displayName: 'Install .NET SDK 3.1'
    inputs:
      packageType: 'sdk'
      version: '3.1.100'

  # 2. Run Tests
  - task: DotNetCoreCLI@2
    displayName: 'Execute Tests'
    inputs:
      command: 'test'
      projects: '**/tests/*/*Tests.csproj'
      arguments: '--configuration release'
    env:
      spotify_clientSecret: $(spotify_clientSecret)

  # 3a. Generate Release Version
  - script: npx semantic-release --verifyConditions "@semantic-release/github" --prepare "" --publish "@semantic-release/github"
    displayName: 'Initialize Semantic Release'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    env:
      GITHUB_TOKEN: $(github_token)

  # 3b. Set Release Version
  - script: |
      Tags=$(git describe --tags)
      IFS='-' read -ra image_versionTag <<< "$Tags"
      echo "##vso[task.setvariable variable=semanticVersion;]${image_versionTag[0]:1}-$(Build.BuildId)"
    displayName: 'Set Release Version Environment Variable'
    condition: ne(variables['Build.Reason'], 'PullRequest')

  # 3c. Set Pull Request Version
  - script: |
      echo "##vso[task.setvariable variable=semanticVersion;]pr-$(Build.BuildId)"
    displayName: 'Set Pull Request Version Environment Variable'
    condition: eq(variables['Build.Reason'], 'PullRequest')

  # 4. Docker Push to ACR
  - script: |
      docker build -t $(docker_server)/$(image_name):$(semanticVersion) .
      docker tag $(docker_server)/$(image_name):$(semanticVersion) $(docker_server)/$(image_name):$(semanticVersion)
      echo "$(docker_password)" | docker login -u $(docker_username) --password-stdin $(docker_server)
      docker push $(docker_server)/$(image_name):$(Build.BuildId)
      docker push $(docker_server)/$(image_name):$(semanticVersion)
    displayName: 'Push to Azure Container Registry'