name: Auto Label

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Set Labels
    runs-on: ubuntu-22.04

    steps:

    - name: A) Checkout
      uses: actions/checkout@v2
      
    - name: B) Labeling
      uses: banyan/auto-label@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
