name: Auto Label

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Set Labels
    runs-on: ubuntu-18.04

    steps:

    - name: A) Telemetry Opt-Out
      run: echo ::set-env name=DOTNET_CLI_TELEMETRY_OPTOUT::1
      
    - name: B) Checkout
      uses: actions/checkout@v2
      
    - name: C) Labeling
      uses: banyan/auto-label@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
