name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    env:
      IMAGE_NAME: uru
      APP_NAME: uruno
      TESTS_PROJECT: URU.Tests/URU.Tests.csproj
    name: Azure Container Registry
    runs-on: ubuntu-18.04

    steps:

    - name: A) Telemetry Opt-Out
      run: echo ::set-env name=DOTNET_CLI_TELEMETRY_OPTOUT::1
      
    - name: B) Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: C) Fetch Tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      
    - name: D) Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - name: E) Run Tests
      run: dotnet test ${{ env.TESTS_PROJECT }} --configuration Release
      working-directory: ./tests
      env:
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

    - name: F) Semantic Release
      run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: G) Set New Release
      run: |
        lastTag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo ::set-env name=RELEASE_VERSION::${lastTag:1}
        
    - name: H) Print Release Version
      run: |
        echo Release Version: ${{ env.RELEASE_VERSION }}

    - name: I) Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: J) Azure Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_NAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: K) Docker Images to Azure Container Registry
      if: success()
      run: |
        echo ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
        docker build -t ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }} --build-arg versionNumber=${{ env.RELEASE_VERSION }} .
        docker tag ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }} ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
        docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
        docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

    - name: L) Deploy to Azure WebApp for Containers
      if: success()
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: ${{ env.APP_NAME }}
        images: ${{ secrets.REGISTRY_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
    
    - name: M) Azure Logout
      if: always()
      run: az logout
